### ISSUE TITLE
Paper/Label

### ISSUE THREAD

**Issue by kerstinvg** [mbarzegary/BioDeg-UI#1]
Hello @mbarzegary,

I have a few suggestions regarding the Paper/Software:

- For me, the term 'scaffold' can lead to misunderstandings, since a scaffold already describes a certain component in medical application. I would suggest changing it to "Degradable Part" or something more general
- On page 4 line 108-109 in the paper probably something went wrong with the citation?
- No statement was made that the code right now is not able to simulated localised corrosion.
- Further, it was not mentioned that there are other commonly used degradation codes (e.g. phenomenological surface-based corrosion model by Grogan et al. 2011)

Thanks

**Comment by mbarzegary** [comment]
hi @kerstinvg,

thank you for the constructive comments. I applied a couple of fixes (mentioned above) to address your comments. 

there was a fundamental mistake in the way I had the references in the paper text, one of which was pointed out by you. actually, I had already cited Grogan work and a couple of other similar codes, but due to this mistake (using comma instead of semicolon to refer to multiple references), they were not in the compiled paper. now the issue is resolved (https://github.com/mbarzegary/BioDeg-UI/commit/342e406f83fd40d14e8b5d02613b20d556e186ec), so they should appear in the final text.
